oksahil/filmoteka-cp8

- src/js/Firebase/fireStorage.js
- src/library.js
> fix onAuthStateChanged

- src/js/library.js
> fix onAuthStateChanged1

- src/js/modal-info-film.js
- src/library.js
Reverts oksahil/filmoteka-cp8#31
> Revert "Feature/watched queue"

- src/index.html
- src/index.js
- src/js/modal-info-film.js
- src/sass/_modal-film.scss
> cool things

- src/index.js
- src/js/fetch-genres.js
Reverts oksahil/filmoteka-cp8#48
> Revert "Update index.js"

- src/js/modal-info-film.js
- src/library.js
- src/sass/_modal-film.scss
- src/sass/switch-color.scss
Reverts oksahil/filmoteka-cp8#55
> Revert "js func"

- src/js/color-switch.js
- src/js/switch-library.js
- src/library.html
- src/partials/header-library.html
- src/sass/_header-library.scss
- src/sass/_switch-color.scss
- src/sass/_switch-library.scss
- src/sass/index.scss
localStorage does not work, but i am thinking about it
> add-switch-library

- src/js/modal-info-film.js
- src/library.js
Reverts oksahil/filmoteka-cp8#58
> Revert "to merge"

- src/library.js
Reverts oksahil/filmoteka-cp8#65
> Revert "library to merge"

- src/library.js
Reverts oksahil/filmoteka-cp8#74
> Revert "library-func-half"

- src/js/modal-info-film.js
- src/library.js
Reverts oksahil/filmoteka-cp8#81
> Revert "library-full"

- src/index.js
- src/js/modal-info-film.js
- src/library.js
Reverts oksahil/filmoteka-cp8#84
> Revert "Library again"

- src/index.js
- src/library.js
Reverts oksahil/filmoteka-cp8#86
> Revert "fix"

- src/library.js
Reverts oksahil/filmoteka-cp8#91
> Revert "library js"

- src/library.js
Reverts oksahil/filmoteka-cp8#93
> Revert "imports"

- src/js/film-template-lib.js
- src/library.js
Reverts oksahil/filmoteka-cp8#95
> Revert "imports1"

- src/js/film-template-lib.js
- src/library.js
Reverts oksahil/filmoteka-cp8#97
> Revert "deleting template lib"

- src/library.js
Reverts oksahil/filmoteka-cp8#100
> Revert "deleting scss"

- src/js/film-templete.js
- src/library.js
Reverts oksahil/filmoteka-cp8#103
> Revert "imports short"

- src/js/film-templete.js
- src/library.js
Reverts oksahil/filmoteka-cp8#105
> Revert "template"

- src/js/film-template-lib.js
- src/library.js
Reverts oksahil/filmoteka-cp8#106
> Revert "libfix"

- src/js/film-templete.js
- src/library.js
Reverts oksahil/filmoteka-cp8#109
> Revert "scss only"

- src/js/film-templete.js
- src/js/modal-info-film.js
- src/library.js
Reverts oksahil/filmoteka-cp8#111
> Revert "binary again"

- src/library.js
Reverts oksahil/filmoteka-cp8#114
> Revert "path"

- src/library.js
Reverts oksahil/filmoteka-cp8#116
> Revert "import dott"

- src/library.js
Reverts oksahil/filmoteka-cp8#118
> Revert "dott src"

- src/library.js
Reverts oksahil/filmoteka-cp8#120
> Revert "template minus"

- src/js/film-templete.js
- src/library.js
Reverts oksahil/filmoteka-cp8#124
> Revert "minus imps"

- src/library.js
Reverts oksahil/filmoteka-cp8#126
> Revert "minus temp"

- src/js/fetch-genres.js
- src/js/modal-info-film.js
- src/library.js
Reverts oksahil/filmoteka-cp8#140
> Revert "deletions"

- src/js/modal-library.js
Reverts oksahil/filmoteka-cp8#158
> Revert "libchange"

- src/js/modal-library.js
Reverts oksahil/filmoteka-cp8#160
> Revert "new"
